### ISSUE TITLE
Add intent unit tests

### ISSUE THREAD

**Issue by mathquis** [rhasspy/rhasspy-server-hermes#1]
From: https://community.rhasspy.org/t/add-intent-tests-to-avoid-breaking-assistant/101

Add the ability to record WAV files and match them with an intent and slots raw texts.

Tests can be stored in a profile `tests` folder.

Tests should be able to be run one at a time or in batch.

Tests are alreay implemented in @synesthesiam [`voice2json`](https://github.com/synesthesiam/voice2json) library.
See: http://voice2json.org/commands.html#test-examples

_Note: The web UI will have to be updated also._

**Comment by synesthesiam** [comment]
/api/evaluate now does this
