### ISSUE TITLE
Documentation missing in docker image

### ISSUE THREAD

**Issue by Daenara** [rhasspy/rhasspy-server-hermes#14]
Evening,

I just noticed that in the 2.5.1 version of the docker image the documentation seems to be missing. The folder is there but here is what is in it:
![image](https://user-images.githubusercontent.com/3619315/88095202-04d73600-cb95-11ea-9a92-3115ddc8d1e7.png)

**Comment by synesthesiam** [comment]
Thanks for catching this. I'm not sure exactly what happened, but I've re-run the script to build the docs and verified they're in the latest Docker image (uploading now).
