### ISSUE TITLE
Running the server from a path other than root

### ISSUE THREAD

**Issue by skateman** [rhasspy/rhasspy-server-hermes#16]
I was wondering if it would be possible to allow the server to run from a path other than root. Right now I have an nginx reverse proxy for `https://homeassistant.local/rhasspy` pointing to `http://homeassistant.local:12101/` but it's not able to load the assets as they are being loaded from `https://homeassistant.local/css` and `https://homeassistant.local/js/`.

It could be implemented using an optional path prefix argument which would default to `/` and it would be populated in the static files somehow.

**Comment by synesthesiam** [comment]
I think this is a good idea. Future me will need to modify `rhasspy-server-hermes` and either add an option or see if Flask/quart can do this automatically.

**Comment by Romkabouter** [comment]
a good idea, because then we can made the Home Assistant Addon work with Ingress as well.
Currently this fails, or it might be my lack of skill as well :D

**Comment by synesthesiam** [comment]
This is working as of 6368dc5a4a1456e87ad70da96be506c4fd4ff247
In 2.5.7, you will be able to add `--http-root /some/prefix` to `rhasspy-voltron` :)
