### ISSUE TITLE
err in ssl option?

### ISSUE THREAD

**Issue by DarielHG89** [rhasspy/rhasspy-server-hermes#20]
hi, im getting an error when i try to run the rhasspy docker image with ssl options, im using this commandline (docker run -it -p 12101:12101 -v "$HOME/.config/rhasspy/profiles:/profiles" -v "/etc/localtime:/etc/localtime:ro" --device /dev/snd:/dev/snd rhasspy/rhasspy --user-profiles /profiles --profile es --certfile cert.pem --keyfile key.pem)

in the log i see that the certs files are not found, where its the directory that i need to use to place the cert and key files?
i placed in:
/home/pi/
/home/pi/.config/rhasspy/
and others and the same result occurs
this is the log:

Starting up...
Using virtual environment at /usr/lib/rhasspy/.venv
DEBUG:rhasspysupervisor:Namespace(debug=True, docker_compose='', local_mqtt_port=12183, profile='es', supervisord_conf='supervisord.conf', system_profiles=None, user_profiles=PosixPath('/profiles'))
DEBUG:rhasspysupervisor:Loading profile es (user=/profiles, system=None)
DEBUG:rhasspyprofile.profile:Loading /usr/lib/rhasspy/rhasspy-profile/rhasspyprofile/profiles/es/profile.json
DEBUG:rhasspyprofile.profile:Loading /profiles/es/profile.json
DEBUG:rhasspysupervisor:Generating supervisord conf
DEBUG:rhasspysupervisor:Microphone disabled (system=dummy)
DEBUG:rhasspysupervisor:Speakers disabled (system=dummy)
DEBUG:rhasspysupervisor:Wake word disabled (system=dummy)
DEBUG:rhasspysupervisor:Intent handling disabled (system=dummy)
DEBUG:rhasspysupervisor:Wrote /profiles/es/supervisord.conf
Starting services...
Using virtual environment at /usr/lib/rhasspy/.venv
Using virtual environment at /usr/lib/rhasspy/.venv
2020-12-31 22:22:08,392 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-12-31 22:22:08,405 INFO supervisord started with pid 181
2020-12-31 22:22:09,412 INFO spawned: 'mqtt' with pid 197
2020-12-31 22:22:09,421 INFO spawned: 'intent_recognition' with pid 198
2020-12-31 22:22:09,436 INFO spawned: 'speech_to_text' with pid 199
2020-12-31 22:22:09,447 INFO spawned: 'dialogue' with pid 200
2020-12-31 22:22:09,464 INFO spawned: 'text_to_speech' with pid 201
1609471329: mosquitto version 1.6.6 starting
1609471329: Using default config.
1609471329: Opening ipv4 listen socket on port 12183.
1609471329: Opening ipv6 listen socket on port 12183.
2020-12-31 22:22:10,624 INFO success: mqtt entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-12-31 22:22:10,624 INFO success: intent_recognition entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-12-31 22:22:10,625 INFO success: speech_to_text entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-12-31 22:22:10,626 INFO success: dialogue entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-12-31 22:22:10,627 INFO success: text_to_speech entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[DEBUG:2020-12-31 22:22:13,165] rhasspytts_cli_hermes: Namespace(debug=True, host='localhost', language='es-la', log_format='[%(levelname)s:%(asctime)s] %(name)s: %(message)s', password=None, play_command=None, port=12183, site_id=['default'], temporary_wav=False, text_on_stdin=False, tls=False, tls_ca_certs=None, tls_cert_reqs='CERT_REQUIRED', tls_certfile=None, tls_ciphers=None, tls_keyfile=None, tls_version=None, tts_command='espeak --stdout -v {lang}', username=None, voices_command="espeak --voices | tail -n +2 | awk '{ print $2,$4 }'", volume=1.0)
[DEBUG:2020-12-31 22:22:13,173] asyncio: Using selector: EpollSelector
[DEBUG:2020-12-31 22:22:13,178] rhasspytts_cli_hermes: Connecting to localhost:12183
1609471333: New connection from 127.0.0.1 on port 12183.
1609471333: New client connected from 127.0.0.1 as auto-B2E87C23-658A-B35B-515C-7E5C16308CCD (p2, c1, k60).
[DEBUG:2020-12-31 22:22:13,225] asyncio: Using selector: EpollSelector
[DEBUG:2020-12-31 22:22:13,232] rhasspytts_cli_hermes: Connected to MQTT broker
[DEBUG:2020-12-31 22:22:13,237] rhasspytts_cli_hermes: Subscribed to rhasspy/tts/getVoices
[DEBUG:2020-12-31 22:22:13,241] rhasspytts_cli_hermes: Subscribed to hermes/audioServer/default/playFinished
[DEBUG:2020-12-31 22:22:13,244] rhasspytts_cli_hermes: Subscribed to hermes/tts/say
[DEBUG:2020-12-31 22:22:13,361] rhasspydialogue_hermes: Namespace(debug=True, group_separator=None, host='localhost', log_format='[%(levelname)s:%(asctime)s] %(name)s: %(message)s', no_sound=['default'], password=None, port=12183, session_timeout=30.0, site_id=['default'], sound=None, tls=False, tls_ca_certs=None, tls_cert_reqs='CERT_REQUIRED', tls_certfile=None, tls_ciphers=None, tls_keyfile=None, tls_version=None, username=None, volume=1.0, wakeword_id=None)
[DEBUG:2020-12-31 22:22:13,362] rhasspydialogue_hermes: Sound is disabled for sites ['default']
[DEBUG:2020-12-31 22:22:13,372] asyncio: Using selector: EpollSelector
[DEBUG:2020-12-31 22:22:13,391] rhasspydialogue_hermes: Connecting to localhost:12183
1609471333: New connection from 127.0.0.1 on port 12183.
1609471333: New client connected from 127.0.0.1 as auto-8023EDCA-8AB8-30AA-0270-33C54BC676BC (p2, c1, k60).
[DEBUG:2020-12-31 22:22:13,538] rhasspydialogue_hermes: Connected to MQTT broker
[DEBUG:2020-12-31 22:22:13,541] asyncio: Using selector: EpollSelector
[DEBUG:2020-12-31 22:22:13,559] rhasspydialogue_hermes: Subscribed to hermes/nlu/intentNotRecognized
[DEBUG:2020-12-31 22:22:13,562] rhasspydialogue_hermes: Subscribed to hermes/dialogueManager/continueSession
[DEBUG:2020-12-31 22:22:13,564] rhasspydialogue_hermes: Subscribed to hermes/audioServer/default/playFinished
[DEBUG:2020-12-31 22:22:13,567] rhasspydialogue_hermes: Subscribed to hermes/intent/#
[DEBUG:2020-12-31 22:22:13,569] rhasspydialogue_hermes: Subscribed to hermes/dialogueManager/endSession
[DEBUG:2020-12-31 22:22:13,604] rhasspydialogue_hermes: Subscribed to hermes/hotword/+/detected
[DEBUG:2020-12-31 22:22:13,611] rhasspydialogue_hermes: Subscribed to hermes/tts/sayFinished
[DEBUG:2020-12-31 22:22:13,622] rhasspydialogue_hermes: Subscribed to hermes/asr/textCaptured
[DEBUG:2020-12-31 22:22:13,624] rhasspydialogue_hermes: Subscribed to hermes/dialogueManager/configure
[DEBUG:2020-12-31 22:22:13,646] rhasspydialogue_hermes: Subscribed to hermes/dialogueManager/startSession
[DEBUG:2020-12-31 22:22:15,902] rhasspyserver_hermes: Namespace(certfile='cert.pem', host='0.0.0.0', keyfile='key.pem', local_mqtt_port=12183, log_format='[%(levelname)s:%(asctime)s] %(name)s: %(message)s', log_level='DEBUG', mqtt_host=None, mqtt_password=None, mqtt_port=None, mqtt_username=None, port=12101, profile='es', set=[], system_profiles=None, url_root='', user_profiles='/profiles', web_dir='/usr/lib/rhasspy/rhasspy-server-hermes/web')
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 194, in <module>
    ssl_context.load_cert_chain(_ARGS.certfile, _ARGS.keyfile)
FileNotFoundError: [Errno 2] No such file or directory
[DEBUG:2020-12-31 22:22:16,786] rhasspynlu_hermes: Namespace(casing='lower', debug=True, host='localhost', intent_graph='/profiles/es/intent_graph.pickle.gz', language='es_ES', log_format='[%(levelname)s:%(asctime)s] %(name)s: %(message)s', no_fuzzy=False, password=None, port=12183, replace_numbers=True, site_id=['default'], tls=False, tls_ca_certs=None, tls_cert_reqs='CERT_REQUIRED', tls_certfile=None, tls_ciphers=None, tls_keyfile=None, tls_version=None, username=None)
[DEBUG:2020-12-31 22:22:16,793] asyncio: Using selector: EpollSelector
[DEBUG:2020-12-31 22:22:16,797] rhasspynlu_hermes: Connecting to localhost:12183
1609471336: New connection from 127.0.0.1 on port 12183.
1609471336: New client connected from 127.0.0.1 as auto-BDEC6518-C607-5E68-0F12-57E861EC105D (p2, c1, k60).
[DEBUG:2020-12-31 22:22:16,835] asyncio: Using selector: EpollSelector
[DEBUG:2020-12-31 22:22:16,838] rhasspynlu_hermes: Connected to MQTT broker
[DEBUG:2020-12-31 22:22:16,841] rhasspynlu_hermes: Subscribed to rhasspy/nlu/default/train
[DEBUG:2020-12-31 22:22:16,845] rhasspynlu_hermes: Subscribed to hermes/nlu/query
[DEBUG:2020-12-31 22:22:17,863] rhasspyasr_pocketsphinx_hermes: Namespace(acoustic_model='/profiles/es/acoustic_model', base_dictionary=['/profiles/es/base_dictionary.txt', '/profiles/es/custom_words.txt'], base_language_model_fst='/profiles/es/base_language_model.fst', base_language_model_weight=0.0, debug=True, dictionary='/profiles/es/dictionary.txt', dictionary_casing='lower', g2p_casing='ignore', g2p_model='/profiles/es/g2p.fst', host='localhost', intent_graph='/profiles/es/intent_graph.pickle.gz', language_model='/profiles/es/language_model.txt', log_format='[%(levelname)s:%(asctime)s] %(name)s: %(message)s', mixed_language_model_fst='/profiles/es/mixed.fst', mllr_matrix=None, no_overwrite_train=False, password=None, port=12183, site_id=['default'], tls=False, tls_ca_certs=None, tls_cert_reqs='CERT_REQUIRED', tls_certfile=None, tls_ciphers=None, tls_keyfile=None, tls_version=None, unknown_words='/profiles/es/unknown_words.txt', username=None, voice_before_seconds=0.5, voice_min_seconds=1.0, voice_sensitivity=1, voice_silence_seconds=0.5, voice_skip_seconds=0.0, voice_speech_seconds=0.3)
[DEBUG:2020-12-31 22:22:17,865] rhasspyasr_pocketsphinx_hermes: Loading Pocketsphinx decoder with (hmm=/profiles/es/acoustic_model, dict=/profiles/es/dictionary.txt, lm=/profiles/es/language_model.txt, mllr=None)
[DEBUG:2020-12-31 22:22:17,873] asyncio: Using selector: EpollSelector
[DEBUG:2020-12-31 22:22:17,881] rhasspyasr_pocketsphinx_hermes: Connecting to localhost:12183
[DEBUG:2020-12-31 22:22:17,916] asyncio: Using selector: EpollSelector
1609471337: New connection from 127.0.0.1 on port 12183.
1609471337: New client connected from 127.0.0.1 as auto-8062F6C8-9071-158F-8C7A-19CB017DCA51 (p2, c1, k60).
[DEBUG:2020-12-31 22:22:17,924] rhasspyasr_pocketsphinx_hermes: Connected to MQTT broker
[DEBUG:2020-12-31 22:22:17,928] rhasspyasr_pocketsphinx_hermes: Subscribed to hermes/asr/toggleOn
[DEBUG:2020-12-31 22:22:17,931] rhasspyasr_pocketsphinx_hermes: Subscribed to rhasspy/g2p/pronounce
[DEBUG:2020-12-31 22:22:17,933] rhasspyasr_pocketsphinx_hermes: Subscribed to hermes/asr/toggleOff
[DEBUG:2020-12-31 22:22:17,935] rhasspyasr_pocketsphinx_hermes: Subscribed to hermes/asr/stopListening
[DEBUG:2020-12-31 22:22:17,937] rhasspyasr_pocketsphinx_hermes: Subscribed to rhasspy/asr/default/train
[DEBUG:2020-12-31 22:22:17,939] rhasspyasr_pocketsphinx_hermes: Subscribed to hermes/audioServer/default/audioFrame
[DEBUG:2020-12-31 22:22:17,942] rhasspyasr_pocketsphinx_hermes: Subscribed to hermes/asr/startListening
[DEBUG:2020-12-31 22:22:17,946] rhasspyasr_pocketsphinx_hermes: Subscribed to hermes/audioServer/default/+/audioSessionFrame

**Comment by synesthesiam** [comment]
Try specifying the full path to each file. You should be able to use the `${RHASSPY_PROFILE_DIR}` environment variable for the directory of your Rhasspy profile (e.g., `~/.config/rhasspy/profiles/en`)

**Comment by DarielHG89** [comment]
hi, i copy the cert and key to the profiles dir and run with the command --certfile /profiles/cert.pem --keyfile /profiles/key.pem, its working now, thanks a lot.
