### ISSUE TITLE
TimeoutError ...

### ISSUE THREAD

**Issue by dikdust** [rhasspy/rhasspy-server-hermes#24]
Hi I'm having this problem.. Everything runs on a rasp3 with home assistant (also hotwords aren't selectable with porcupine and others) usb microphone . I'm asking too much to rasp or there are other problems ?

[DEBUG:2021-06-21 19:45:37,060] rhasspyserver_hermes: -> HotwordDetected(model_id='default', model_version='', model_type='personal', current_sensitivity=1.0, site_id='default', session_id=None, send_audio_captured=None, lang=None, custom_entities=None)
[DEBUG:2021-06-21 19:45:37,062] rhasspyserver_hermes: Publishing 199 bytes(s) to hermes/hotword/default/detected
[DEBUG:2021-06-21 19:45:37,067] rhasspyserver_hermes: Waiting for intent (session_id=None)
[ERROR:2021-06-21 19:46:07,096] rhasspyserver_hermes: 
Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 936, in api_listen_for_command
    async for response in core.publish_wait(handle_intent(), [], message_types):
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 994, in publish_wait
    result_awaitable, timeout=timeout_seconds
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

**Comment by brad999** [comment]
Did you ever find a resolution to this? 

When I have my intent recognition set to remote HTTP I get this exact error. Local intent recognition works fine and I can manually call the base station API just fine but when Rhasspy tries to do it I get this error.

**Comment by centic9** [comment]
For me such TimeoutErrors were resolved when I enabled all the integrations in the settings.

**Comment by dikdust** [comment]
I will close it since I have switched all architecture on a pi4 and everything work. So I'm guessing that was an hardware issue ...
