### ISSUE TITLE
Quart app.run usage leads to high CPU

### ISSUE THREAD

**Issue by tuxedo78** [rhasspy/rhasspy-server-hermes#8]
Hi,

According to [Quart github issue](https://github.com/pgjones/quart/issues/104), `app.run` should not be used for production because it permanently monitors files for reloading.

A 1st workaround is to add the flag `use_reloader=False` to **app.run** but waybe we should go with hypercorn instead (I did not try this option but it's the one recommended by Quart dev)? By the way, the current Docker images have Hypercorn 0.9.5 which is less optimized than hypercorn 0.10.1.

**Comment by pgjones** [comment]
See also [this deployment documentation](https://pgjones.gitlab.io/quart/tutorials/deployment.html) - Please let me know if things are unclear.

**Comment by pgjones** [comment]
Actually, having looked at your usage I think you really want to use [this functionality](https://pgjones.gitlab.io/hypercorn/how_to_guides/api_usage.html) as you wish to control how Quart is run.

**Comment by tuxedo78** [comment]
Can you propose a patch? I'm ready to test it on my side

**Comment by synesthesiam** [comment]
Thank you, @pgjones for responding and for Quart itself! Your docs are quite clear that the development server should not be used for deployment, so this is definitely on me :/

I'll test out hypercorn here soon and see if I can make this work.

**Comment by synesthesiam** [comment]
Hypercorn is now used for the web server: 3055e2e207c3d17cd00695d760265a7a9674e535
