### ISSUE TITLE
NoneType TypeError on manual installation without pocketsphinx

### ISSUE THREAD

**Issue by alexbarcelo** [rhasspy/rhasspy-server-hermes#9]
I am installing rhasspy in a "dumb-ish satellite" (only porcupine, external MQTT for all hermes) and was following the [virtual environment installation instructions](https://rhasspy.readthedocs.io/en/latest/installation/#virtual-environment).

The installation procedure works, and I can start everything. However, when I try to access http://<host>:12101/settings I get the following error:

```
  File "/root/rhasspy/.venv/share/rhasspy/templates/settings.html", line 882, in block "body"
    <li>Base Language Model FST: <tt>{{ profile.read_path(profile.get("speech_to_text.pocketsphinx.base_language_model_fst")) }}</tt> </li>
  File "/root/rhasspy/.venv/lib/python3.7/site-packages/rhasspyprofile/profile.py", line ###, in read_path
    full_path = profiles_dir.joinpath(self.name, *path_parts)
  File "/usr/lib/python3.7/pathlib.py", line 898, in joinpath
    return self._make_child(args)
  File "/usr/lib/python3.7/pathlib.py", line 688, in _make_child
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.7/pathlib.py", line 642, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I debugged a little bit and the HTML rendering is failing at this point:

https://github.com/rhasspy/rhasspy-server-hermes/blob/3f4dc939a8f4e12d7f6674b486c88e0ca71e8f15/templates/settings.html#L882

Specifically, the [`profile.get`](https://github.com/rhasspy/rhasspy-profile/blob/bb4c81aab1f1b6cda42bbb89958937a7d14d50f0/rhasspyprofile/profile.py#L75) method is being called with:
 - `path='speech_to_text.pocketsphinx.base_language_model_fst'`
 - `default=None` 

The `get` method returns a `None` value, and the [`read_path` method](https://github.com/rhasspy/rhasspy-profile/blob/bb4c81aab1f1b6cda42bbb89958937a7d14d50f0/rhasspyprofile/profile.py#L121) is getting `(None,)` (a tuple of one element with the None object).

I am using Python 3.7.3 with the master branch of rhasspy. The installation was done with:

    $ ./configure RHASSPY_WAKE_SYSTEM=porcupine --disable-speech-to-text --disable-training --disable-fuzzywuzzy --disable-nanotts
    $ make && make install

Apologies if this issue should be somewhere else, I saw that both the template here and the rhasspy-profile were involved in the error but I lacked insight on how to follow-up troubleshooting and finding the root of the problem.

**Comment by Romkabouter** [comment]
I also ran into this issue

**Comment by alexbarcelo** [comment]
I definetely missed https://github.com/rhasspy/rhasspy/issues/66

Closing as duplicate.
